services:
  mysql:
    image: mysql:8.0
    container_name: demogorm
    restart: always
    environment:
      TZ: Asia/Bangkok
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: gorm
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: demo-gorm
    ports:
      - "3308:3306"

